{% set name = "multiregex" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/multiregex-{{ version }}.tar.gz
  sha256: d3739c4be5583f8b973452f426fc12bb399ca9ba7e28fa696d00d618d12aae5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
    - flit-core >=3.2,<4
  run:
    - pyahocorasick
    - python >=3.6

test:
  imports:
    - multiregex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Quantco/multiregex
  summary: Speed up regex matching with non-regex substring "prematchers", similar to Bloom filters.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 0xbe7a
    - ivergara
    - jonashaag
